### ISSUE TITLE
Google Cal has a "VALARM" tag that breaks import/read

### ISSUE THREAD

**Issue by BearlyDoug** [matiasperrone/ical-easy-reader#5]
> BEGIN:VALARM
> ACTION:DISPLAY
> DESCRIPTION:This is an event reminder
> TRIGGER:-P0DT0H10M0S
> END:VALARM

This has been confirmed. Once I remove the items above from the .ics file, everything works great.

I'm attaching a Google Calendar file for testing
[google.ics.txt](https://github.com/matiasperrone/ical-easy-reader/files/6598566/google.ics.txt)

Thanks!

**Comment by matiasperrone** [comment]
Can you check the new v2.0.1 version and see if the error is correct?

**Comment by matiasperrone** [comment]
The UID `74pe2dkhupmlmh1v61o1jjumav@google.com` is the one with errors, but check this code

```php
<?php

require 'iCalEasyReader.php';

$ical = file_get_contents(__DIR__ . '/google.ics');
$ical = (new iCalEasyReader)->load($ical, false);

echo json_encode($ical, JSON_PRETTY_PRINT);
```

**Comment by BearlyDoug** [comment]
Here's the latest:

> PHP Fatal error:  Uncaught Error: Call to undefined function mb_str_split() in calendarTest/iCalEasyReader.php:72
> Stack trace:
> #0 [internal function]: iCalEasyReader->convertCaracters('PRODID', 0)
> #1 calendarTest/iCalEasyReader.php(137): array_walk(Array, Array)
> #2 calendarTest/iCalEasyReader.php(210): iCalEasyReader->addItem(Array, 'PRODID:-//Googl...')
> #3 calendarTest/iCalEasyReader.php(58): iCalEasyReader->processCalendar(Array, true)
> #4 calendarTest/index.php(8): iCalEasyReader->load('BEGIN:VCALENDAR...')
> #5 {main}
>   thrown in calendarTest/iCalEasyReader.php on line 72

Line 72:
>		$chars = mb_str_split($data);

**Comment by matiasperrone** [comment]
This package depends on Multibyte string functions, in order to support different file encodings, that why you're having this fatal error
